# Generated by Django 2.2.8 on 2020-04-19 22:41

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo ?')),
                ('servico', models.TextField(max_length=100, verbose_name='Servico')),
                ('descricao', models.TextField(max_length=100, verbose_name='Decrição')),
                ('item1', models.TextField(max_length=30, verbose_name='Item 1')),
                ('item2', models.TextField(max_length=30, verbose_name='Item 2')),
                ('imagem', stdimage.models.StdImageField(upload_to='servicos', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo ?')),
                ('titulo', models.TextField(max_length=100, verbose_name='Titulo')),
                ('texto', models.TextField(max_length=100, verbose_name='Texto')),
                ('pessoa', models.TextField(max_length=40, verbose_name='Pessoa')),
                ('topico', models.TextField(max_length=100, verbose_name='Tópico')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('fas fa-binoculars fa-stack-1x', 'binoculos'), ('fas fa-list-alt fa-stack-1x', 'lista'), ('fas fa-chart-pie fa-stack-1x', 'grafico pizza')], max_length=12, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Sobre',
                'verbose_name_plural': 'Sobre',
            },
        ),
    ]
