# Generated by Django 2.2.8 on 2020-04-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sobretopico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo ?')),
                ('topico', models.CharField(max_length=100, verbose_name='Tópico')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('fas fa-binoculars fa-stack-1x', 'binoculos'), ('fas fa-list-alt fa-stack-1x', 'lista'), ('fas fa-chart-pie fa-stack-1x', 'grafico pizza')], max_length=12, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Sobretopico',
                'verbose_name_plural': 'Sobretopicos',
            },
        ),
        migrations.RemoveField(
            model_name='sobre',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='sobre',
            name='icone',
        ),
        migrations.RemoveField(
            model_name='sobre',
            name='topico',
        ),
        migrations.AlterField(
            model_name='servicos',
            name='item1',
            field=models.CharField(max_length=30, verbose_name='Item 1'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='item2',
            field=models.CharField(max_length=30, verbose_name='Item 2'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='servico',
            field=models.CharField(max_length=100, verbose_name='Servico'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='pessoa',
            field=models.CharField(max_length=40, verbose_name='Pessoa'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='texto',
            field=models.TextField(max_length=500, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
    ]
