# Generated by Django 2.2.8 on 2020-04-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200419_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobretopico',
            name='icone',
            field=models.TextField(choices=[('fas fa-binoculars fa-stack-1x', 'binoculos'), ('fas fa-list-alt fa-stack-1x', 'lista'), ('fas fa-chart-pie fa-stack-1x', 'grafico pizza')], max_length=30, verbose_name='Icone'),
        ),
    ]
