# Generated by Django 2.2.8 on 2020-04-19 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200419_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sobretopico',
            name='icone',
        ),
    ]
