# Generated by Django 2.2.8 on 2020-04-19 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_sobretopico_icone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sobretopico',
            old_name='topico',
            new_name='sobretopico',
        ),
    ]
