# Generated by Django 2.2.8 on 2020-04-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200419_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobretopico',
            name='icone',
            field=models.TextField(choices=[('fas fa-binoculars fa-stack-1x', 'binoculos'), ('fas fa-list-alt fa-stack-1x', 'lista'), ('fas fa-list-alt fa-stack-1x', 'grafico pizza'), ('fas fa-truck', 'caminhão')], default=1, max_length=12, verbose_name='Icone'),
            preserve_default=False,
        ),
    ]
