# Generated by Django 2.2.8 on 2020-04-20 11:07

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200419_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to='servicos', verbose_name='Imagem'),
        ),
    ]
