# Generated by Django 2.2.8 on 2020-04-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200420_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subservicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo ?')),
                ('subservico', models.CharField(max_length=100, verbose_name='Subserviço')),
                ('topico1', models.CharField(max_length=100, verbose_name='Topico 1 ')),
                ('descricao1', models.TextField(max_length=140, verbose_name='Descrição 1')),
                ('topico2', models.CharField(max_length=100, verbose_name='Topico 2 ')),
                ('descricao2', models.TextField(max_length=140, verbose_name='Descrição 2')),
                ('topico3', models.CharField(max_length=100, verbose_name='Topico 3')),
                ('descricao3', models.TextField(max_length=140, verbose_name='Descrição 3')),
            ],
            options={
                'verbose_name': 'Subservico',
                'verbose_name_plural': 'Subservicos',
            },
        ),
    ]
