# Generated by Django 2.2.8 on 2020-04-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_subservicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobretopico',
            name='icone',
            field=models.TextField(choices=[('fa-binoculars', 'binoculos'), ('fa-list-alt', 'lista'), ('fa-chart-pie', 'grafico pizza'), ('fa-truck', 'caminhão'), ('fa-warehouse', 'armazem')], max_length=12, verbose_name='Icone'),
        ),
    ]
