# Generated by Django 2.2.8 on 2020-04-22 18:30

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_projetos'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='imagem',
            field=stdimage.models.StdImageField(default=1, upload_to=core.models.get_file_path, verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
