# Generated by Django 2.2.8 on 2020-04-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_projetos_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='area3',
            field=models.TextField(blank=True, choices=[('originacao', 'Originação'), ('abast', 'Abastecimento'), ('impexp', 'Importação e Exportação'), ('logistica', 'Logística')], max_length=12, verbose_name='Area3'),
        ),
        migrations.AddField(
            model_name='projetos',
            name='area4',
            field=models.TextField(blank=True, choices=[('originacao', 'Originação'), ('abast', 'Abastecimento'), ('impexp', 'Importação e Exportação'), ('logistica', 'Logística')], max_length=12, verbose_name='Area4'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='area2',
            field=models.TextField(blank=True, choices=[('originacao', 'Originação'), ('abast', 'Abastecimento'), ('impexp', 'Importação e Exportação'), ('logistica', 'Logística')], max_length=12, verbose_name='Area2'),
        ),
    ]
