# Generated by Django 2.2.8 on 2020-04-22 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_projetos_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetos',
            name='link',
        ),
    ]
