# Generated by Django 2.2.8 on 2020-04-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200423_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='descricao2',
            field=models.TextField(default=2, max_length=250, verbose_name='Descrição Paragrafo 2'),
            preserve_default=False,
        ),
    ]
