# Generated by Django 2.2.8 on 2020-04-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200423_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetos',
            name='descricao2',
        ),
    ]
