# Generated by Django 2.2.8 on 2020-04-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_projetos_descricao2'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='descricao2',
            field=models.TextField(blank=True, max_length=250, verbose_name='Descrição Paragrafo 2'),
        ),
    ]
