# Generated by Django 2.2.8 on 2020-04-23 14:37

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_projetos_descricao2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subprojetos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo ?')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('topico1', models.CharField(max_length=100, verbose_name='Tópico 1')),
                ('topico2', models.CharField(max_length=100, verbose_name='Tópico 2')),
                ('imagem', stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Subprojeto',
                'verbose_name_plural': 'Subprojetos',
            },
        ),
    ]
