# Generated by Django 2.2.8 on 2020-04-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_subprojetos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inicial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo ?')),
                ('inicio', models.CharField(max_length=100, verbose_name='Ínicio')),
                ('palavras', models.CharField(max_length=100, verbose_name='Palavras')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Inicial',
                'verbose_name_plural': 'Iniciais',
            },
        ),
    ]
