# Generated by Django 2.2.8 on 2020-04-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inicial',
            name='descricao',
            field=models.TextField(max_length=150, verbose_name='Descrição'),
        ),
    ]
