# Generated by Django 2.2.8 on 2020-04-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200423_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprojetos',
            name='descricao',
            field=models.TextField(max_length=150, verbose_name='Descrição'),
        ),
    ]
