# Generated by Django 2.2.8 on 2020-06-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusuario',
            name='ativo',
        ),
    ]
