# Generated by Django 4.0.1 on 2022-06-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_customusuario_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
