# Generated by Django 2.2.8 on 2020-06-13 15:47

import corretora.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cidade', models.CharField(max_length=40, unique=True, verbose_name='Cidade')),
                ('estado', models.TextField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernanbuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RS', 'Rio Grande do Sul'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=12, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['cidade'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('nome_fantasia', models.CharField(max_length=50, verbose_name='Nome Fantasia')),
                ('cnpj_cpf', models.CharField(help_text='digite apenas números', max_length=14, null=True, unique=True, verbose_name='CNPJ/CPF')),
                ('insc_estadual', models.CharField(help_text='digite apenas números', max_length=10, null=True, unique=True, verbose_name='Inscrição Estadual')),
                ('telefone', models.CharField(help_text='digite apenas números', max_length=11, null=True, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('estado', models.TextField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernanbuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RS', 'Rio Grande do Sul'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=12, verbose_name='Estado')),
                ('obs', models.TextField(blank=True, max_length=125, verbose_name='Observação')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corretora.Cidade')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cnpj_cpf', models.CharField(help_text='digite apenas números', max_length=14, null=True, unique=True, verbose_name='CNPJ/CPF')),
                ('insc_estadual', models.CharField(help_text='digite apenas números', max_length=10, null=True, unique=True, verbose_name='Inscrição Estadual')),
                ('banco', models.CharField(blank=True, max_length=10, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, max_length=5, verbose_name='Agencia')),
                ('conta', models.CharField(blank=True, max_length=12, verbose_name='Conta')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('estado', models.TextField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernanbuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RS', 'Rio Grande do Sul'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=12, verbose_name='Estado')),
                ('obs', models.TextField(blank=True, max_length=125, verbose_name='Observação')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corretora.Cidade')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=20, unique=True, verbose_name='Nome')),
                ('estado', models.TextField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernanbuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RS', 'Rio Grande do Sul'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=12, verbose_name='Estado')),
                ('contato', models.CharField(blank=True, max_length=30, verbose_name='Contato')),
                ('telefone', models.CharField(blank=True, help_text='digite apenas números', max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=30, verbose_name='E-mail')),
                ('obs', models.TextField(blank=True, max_length=125, verbose_name='Observação')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corretora.Cidade')),
            ],
            options={
                'verbose_name': 'Transportadora',
                'verbose_name_plural': 'Transportadoras',
                'ordering': ['criados', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('contrato', corretora.models.NameField(max_length=9, unique=True, verbose_name='Numero')),
                ('situacao', models.CharField(choices=[('a', 'Aberto'), ('b', 'Fechado'), ('c', 'Cancelado')], default='Aberto', max_length=12, verbose_name='Situação')),
                ('data', models.DateField(default=django.utils.timezone.now, help_text='dd/mm/aaaa')),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço Produto')),
                ('preco_frete', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Frete')),
                ('comissaoc', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Comissão C')),
                ('comissaof', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Comissão F')),
                ('prazopgto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Prazo Pgto')),
                ('modalidadepgto', models.CharField(blank=True, max_length=30, null=True, verbose_name='Mod. Pgto')),
                ('renda', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Renda')),
                ('inteiro', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Inteiro')),
                ('impureza', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Impureza')),
                ('umidade', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Umidade')),
                ('gessado', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Gessado')),
                ('bbranca', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='B. Branca')),
                ('amarelo', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Amarelo')),
                ('manchpic', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Manch/ Pic')),
                ('vermelhos', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Vermelhos')),
                ('variedade', models.CharField(max_length=12, verbose_name='Variedade')),
                ('produto', models.CharField(choices=[('Arroz em Casca', 'Arroz em Casca'), ('Arroz Beneficiado', 'Arroz Benenficiado')], default='Arroz em Casca', max_length=17, verbose_name='Produto')),
                ('tipo', models.CharField(choices=[('Saco 50Kg', 'Saco 50Kg'), ('Fardo 30Kg', 'Fardo 30Kg'), ('Big Bag', 'Big Bag')], default='Saco 50Kg', max_length=12, verbose_name='Tipo')),
                ('quantidade_pedido', models.PositiveIntegerField(help_text='Peso em Tonelada', verbose_name='Quantidade Pedido')),
                ('obs', models.TextField(blank=True, max_length=125, verbose_name='Observação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corretora.Cliente')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corretora.Fornecedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['data', 'cliente', 'situacao'],
            },
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.BooleanField(default=False, verbose_name='Ordem')),
                ('tac', models.BooleanField(default=False, verbose_name='TAC')),
                ('data', models.DateField(help_text='dd/mm/aaaa')),
                ('buonny', models.CharField(max_length=15, verbose_name='Buonny')),
                ('situacao', models.CharField(choices=[('Agendado', 'Agendado'), ('Carregado', 'Carregado')], default='Agendado', max_length=12, verbose_name='Situação')),
                ('placa', models.CharField(max_length=7, verbose_name='Placa')),
                ('motorista', models.CharField(max_length=20, verbose_name='Motorista')),
                ('peso', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Peso')),
                ('veiculo', models.IntegerField(choices=[(51000, 'Rodotrem'), (39000, 'Bitrem'), (37000, 'Bicaçamba'), (36000, 'Vanderléia'), (32000, 'LS Trucada'), (28000, 'Toco')], verbose_name='Veículo')),
                ('valor_mot', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Frete')),
                ('notafiscal', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='NF')),
                ('notafiscal2', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='NF 2')),
                ('valornf', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor NF')),
                ('renda', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Renda')),
                ('inteiro', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Inteiro')),
                ('impureza', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Impureza')),
                ('umidade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Umidade')),
                ('gessado', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Gessado')),
                ('bbranca', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='B.Branca')),
                ('amarelo', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Amarelo')),
                ('manchpic', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Manch/Pic')),
                ('vermelhos', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Vermelhos')),
                ('obs', models.TextField(blank=True, max_length=125, verbose_name='Observação')),
                ('pedido', models.ForeignKey(limit_choices_to={'situacao': 'a'}, on_delete=django.db.models.deletion.PROTECT, to='corretora.Pedido')),
                ('transp', models.ForeignKey(default=corretora.models.get_default_transp_name, on_delete=django.db.models.deletion.PROTECT, to='corretora.Transportadora')),
            ],
            options={
                'verbose_name': 'Carga',
                'verbose_name_plural': 'Cargas',
                'ordering': ['situacao', 'data'],
            },
        ),
    ]
