# Generated by Django 2.2.8 on 2020-06-24 10:47

import corretora.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='pgcomissao',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
        migrations.AddField(
            model_name='carga',
            name='vpcomissaoc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Valor Comissao'),
        ),
        migrations.AddField(
            model_name='carga',
            name='vpcomissaof',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Valor Comissao F'),
        ),
        migrations.AlterField(
            model_name='carga',
            name='notafiscal',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='NF'),
        ),
        migrations.AlterField(
            model_name='carga',
            name='notafiscal2',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='NF 2'),
        ),
        migrations.AlterField(
            model_name='carga',
            name='placa',
            field=corretora.models.NameField(max_length=7, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='agencia',
            field=models.CharField(blank=True, help_text='digite apenas números', max_length=5, verbose_name='Agencia'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='conta',
            field=models.CharField(blank=True, help_text='digite apenas números', max_length=12, verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='insc_estadual',
            field=models.CharField(help_text='digite apenas números', max_length=13, null=True, unique=True, verbose_name='Inscrição Estadual'),
        ),
    ]
