# Generated by Django 2.2.8 on 2020-07-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0004_auto_20200624_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='chegada',
            field=models.BooleanField(default=False, verbose_name='Chegou'),
        ),
    ]
