# Generated by Django 2.2.8 on 2020-07-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0005_carga_chegada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='motorista',
            field=models.CharField(max_length=25, verbose_name='Motorista'),
        ),
    ]
