# Generated by Django 2.2.8 on 2020-08-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0008_auto_20200725_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='obs',
            field=models.TextField(blank=True, max_length=500, verbose_name='Observação'),
        ),
    ]
