# Generated by Django 2.2.8 on 2020-09-21 10:54

import corretora.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0009_auto_20200814_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='placa',
            field=corretora.models.NameField(help_text='Somente dígitos', max_length=7, verbose_name='Placa'),
        ),
    ]
