# Generated by Django 2.2.8 on 2020-10-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0010_auto_20200921_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='manchpic',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Man / Pic'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='preco_produto',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='R$ Produto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='quantidade_pedido',
            field=models.PositiveIntegerField(help_text='Peso em Kg', verbose_name='Quant. Pedido'),
        ),
    ]
