# Generated by Django 2.2.8 on 2020-11-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0013_auto_20201028_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='color',
            field=models.CharField(default='whitesmoke', max_length=20, verbose_name='Cor'),
        ),
    ]
