# Generated by Django 2.2.8 on 2020-12-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0014_cliente_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='obs',
            field=models.TextField(blank=True, max_length=500, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='obs',
            field=models.TextField(blank=True, max_length=500, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='obs',
            field=models.TextField(blank=True, max_length=500, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='obs',
            field=models.TextField(blank=True, max_length=500, verbose_name='Observação'),
        ),
    ]
