# Generated by Django 2.2.8 on 2021-01-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0016_carga_data_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='data_agenda',
            field=models.DateField(blank=True, default=None, help_text='dd/mm/aaaa', null=True, verbose_name='Data'),
        ),
    ]
