# Generated by Django 2.2.8 on 2021-01-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0017_auto_20210118_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualização'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualização'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualização'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualização'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualização'),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualização'),
        ),
    ]
