# Generated by Django 2.2.8 on 2021-01-26 17:37

import corretora.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corretora', '0018_auto_20210125_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCarga',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criados', models.DateTimeField(blank=True, editable=False, verbose_name='Criação')),
                ('modificado', models.DateTimeField(blank=True, editable=False, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('chegada', models.BooleanField(default=False, verbose_name='Chegou')),
                ('ordem', models.BooleanField(default=False, verbose_name='Ordem')),
                ('tac', models.BooleanField(default=False, verbose_name='TAC')),
                ('data', models.DateField(help_text='dd/mm/aaaa')),
                ('data_agenda', models.DateField(blank=True, default=None, help_text='dd/mm/aaaa', null=True, verbose_name='Data')),
                ('buonny', models.CharField(max_length=15, verbose_name='Buonny')),
                ('situacao', models.CharField(choices=[('Agendado', 'Agendado'), ('Carregado', 'Carregado')], default='Agendado', max_length=12, verbose_name='Situação')),
                ('placa', corretora.models.NameField(help_text='Somente dígitos', max_length=7, verbose_name='Placa')),
                ('motorista', models.CharField(max_length=25, verbose_name='Motorista')),
                ('peso', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Peso')),
                ('veiculo', models.IntegerField(choices=[(51000, 'Rodotrem'), (39000, 'Bitrem'), (36900, 'Bicaçamba'), (36000, 'Vanderléia'), (33000, 'LS Trucada'), (25500, 'Toco')], verbose_name='Veículo')),
                ('valor_mot', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Frete')),
                ('notafiscal', models.CharField(blank=True, db_index=True, max_length=8, null=True, verbose_name='NF')),
                ('notafiscal2', models.CharField(blank=True, db_index=True, max_length=8, null=True, verbose_name='NF 2')),
                ('valornf', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor NF')),
                ('pgcomissao', models.BooleanField(default=False, verbose_name='Pago')),
                ('vpcomissaoc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Valor Comissao')),
                ('vpcomissaof', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Valor Comissao F')),
                ('renda', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Renda')),
                ('inteiro', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Inteiro')),
                ('impureza', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Impureza')),
                ('umidade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Umidade')),
                ('gessado', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Gessado')),
                ('bbranca', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='B.Branca')),
                ('amarelo', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Amarelo')),
                ('manchpic', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Manch/Pic')),
                ('vermelhos', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Vermelhos')),
                ('obs', models.TextField(blank=True, max_length=500, verbose_name='Observação')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'situacao': 'a'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corretora.Pedido')),
                ('transp', models.ForeignKey(blank=True, db_constraint=False, default=corretora.models.get_default_transp_name, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corretora.Transportadora')),
            ],
            options={
                'verbose_name': 'historical Carga',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
