# Generated by Django 2.2.8 on 2021-01-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0019_historicalcarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dias_descarga',
            field=models.PositiveIntegerField(default=3, verbose_name='Descarga do Dia Carregamento'),
        ),
    ]
