# Generated by Django 2.2.8 on 2021-02-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0020_cliente_dias_descarga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carga',
            options={'ordering': ['situacao', '-data'], 'verbose_name': 'Carga', 'verbose_name_plural': 'Cargas'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='veiculos_dia',
            field=models.PositiveIntegerField(default=10, verbose_name='Veiculos Dia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dias_descarga',
            field=models.PositiveIntegerField(default=3, verbose_name='Desc. do Carr.'),
        ),
    ]
