# Generated by Django 2.2.8 on 2021-02-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0021_auto_20210201_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dias_descarga',
            field=models.PositiveIntegerField(default=3, help_text='dias para a descarga do carregamento', verbose_name='Desc. do Carr.'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='veiculos_dia',
            field=models.PositiveIntegerField(default=10, help_text='máximo veículos descarga por dia', verbose_name='Veiculos Dia'),
        ),
    ]
