# Generated by Django 2.2.8 on 2021-02-02 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corretora', '0022_auto_20210201_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDatasemcarga',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criados', models.DateTimeField(blank=True, editable=False, verbose_name='Criação')),
                ('modificado', models.DateTimeField(blank=True, editable=False, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_semcarga', models.DateField(help_text='dd/mm/aaaa | Data Sem Descarga', verbose_name='Data')),
                ('obs', models.TextField(blank=True, max_length=500, verbose_name='Observação')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corretora.Cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Data Sem Descarga',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Datasemcarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_semcarga', models.DateField(help_text='dd/mm/aaaa | Data Sem Descarga', verbose_name='Data')),
                ('obs', models.TextField(blank=True, max_length=500, verbose_name='Observação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corretora.Cliente')),
            ],
            options={
                'verbose_name': 'Data Sem Descarga',
                'verbose_name_plural': 'Datas Sem Descarga',
                'ordering': ['-data_semcarga'],
            },
        ),
    ]
