# Generated by Django 2.2.8 on 2021-03-24 12:43

import corretora.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corretora', '0024_auto_20210202_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-data', 'situacao', 'cliente'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='transportadora',
            options={'ordering': ['nome'], 'verbose_name': 'Transportadora', 'verbose_name_plural': 'Transportadoras'},
        ),
        migrations.CreateModel(
            name='HistoricalPedido',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criados', models.DateTimeField(blank=True, editable=False, verbose_name='Criação')),
                ('modificado', models.DateTimeField(blank=True, editable=False, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('contrato', corretora.models.NameField(db_index=True, max_length=9, verbose_name='Numero')),
                ('situacao', models.CharField(choices=[('a', 'Aberto'), ('b', 'Fechado'), ('c', 'Cancelado')], default='Aberto', max_length=12, verbose_name='Situação')),
                ('data', models.DateField(default=django.utils.timezone.now, help_text='dd/mm/aaaa')),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='R$ Produto')),
                ('preco_frete', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Frete')),
                ('comissaoc', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Comissão C')),
                ('comissaof', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Comissão F')),
                ('prazopgto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Prazo Pgto')),
                ('modalidadepgto', models.CharField(blank=True, max_length=30, null=True, verbose_name='Mod. Pgto')),
                ('renda', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Renda')),
                ('inteiro', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Inteiro')),
                ('impureza', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Impureza')),
                ('umidade', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Umidade')),
                ('gessado', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Gessado')),
                ('bbranca', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='B. Branca')),
                ('amarelo', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Amarelo')),
                ('manchpic', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Man / Pic')),
                ('vermelhos', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Vermelhos')),
                ('variedade', models.CharField(max_length=12, verbose_name='Variedade')),
                ('produto', models.CharField(choices=[('Arroz em Casca', 'Arroz em Casca'), ('Arroz Beneficiado', 'Arroz Beneficiado'), ('Semente', 'Semente')], default='Arroz em Casca', max_length=17, verbose_name='Produto')),
                ('tipo', models.CharField(choices=[('Saco 50Kg', 'Saco 50Kg'), ('Saco 40Kg', 'Saco 40Kg'), ('Fardo 30Kg', 'Fardo 30Kg'), ('Big Bag', 'Big Bag')], default='Saco 50Kg', max_length=12, verbose_name='Tipo')),
                ('quantidade_pedido', models.PositiveIntegerField(help_text='Peso em Kg', verbose_name='Quant. Pedido')),
                ('obs', models.TextField(blank=True, max_length=500, verbose_name='Observação')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corretora.Cliente')),
                ('fornecedor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corretora.Fornecedor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Pedido',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
