# Generated by Django 2.2.8 on 2021-07-19 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corretora', '0025_auto_20210324_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoVp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cartao_numero', models.CharField(help_text='Somente os 16 números', max_length=16, unique=True, verbose_name='Número do Cartão')),
                ('cartao_utilizado', models.BooleanField(default=False, help_text='Informar se o cartão já foi utilizado', verbose_name='Cartão já Utilizado?')),
                ('obs', models.TextField(blank=True, max_length=500, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartoēs',
                'ordering': ['cartao_numero'],
            },
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='produto',
            field=models.CharField(choices=[('Arroz em Casca', 'Arroz em Casca'), ('Arroz Beneficiado', 'Arroz Beneficiado'), ('Semente', 'Semente'), ('Acucar', 'Açucar')], default='Arroz em Casca', max_length=17, verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='produto',
            field=models.CharField(choices=[('Arroz em Casca', 'Arroz em Casca'), ('Arroz Beneficiado', 'Arroz Beneficiado'), ('Semente', 'Semente'), ('Acucar', 'Açucar')], default='Arroz em Casca', max_length=17, verbose_name='Produto'),
        ),
        migrations.CreateModel(
            name='HistoricalCartaoVp',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criados', models.DateTimeField(blank=True, editable=False, verbose_name='Criação')),
                ('modificado', models.DateTimeField(blank=True, editable=False, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cartao_numero', models.CharField(db_index=True, help_text='Somente os 16 números', max_length=16, verbose_name='Número do Cartão')),
                ('cartao_utilizado', models.BooleanField(default=False, help_text='Informar se o cartão já foi utilizado', verbose_name='Cartão já Utilizado?')),
                ('obs', models.TextField(blank=True, max_length=500, verbose_name='Observação')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cartão',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
