# Generated by Django 2.2.8 on 2021-07-19 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0026_auto_20210719_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartaovp',
            options={'ordering': ['cartao_numero'], 'verbose_name': 'Cartão VP', 'verbose_name_plural': 'Cartoēs VP'},
        ),
        migrations.AlterModelOptions(
            name='historicalcartaovp',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Cartão VP'},
        ),
    ]
