# Generated by Django 2.2.8 on 2021-07-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0027_auto_20210719_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaovp',
            name='cartao_base',
            field=models.CharField(choices=[('palmares', 'Palmares'), ('rio_grande', 'Granjas - RG'), ('jaguarao', 'Jaguarão')], default='Palmares', max_length=17, verbose_name='Local Cartão'),
        ),
        migrations.AddField(
            model_name='historicalcartaovp',
            name='cartao_base',
            field=models.CharField(choices=[('palmares', 'Palmares'), ('rio_grande', 'Granjas - RG'), ('jaguarao', 'Jaguarão')], default='Palmares', max_length=17, verbose_name='Local Cartão'),
        ),
    ]
