# Generated by Django 2.2.8 on 2021-07-25 19:01

import corretora.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0028_auto_20210719_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartaovp',
            options={'verbose_name': 'Cartão VP', 'verbose_name_plural': 'Cartoēs VP'},
        ),
        migrations.AddField(
            model_name='carga',
            name='obs_comissao',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observação Comissão'),
        ),
        migrations.AddField(
            model_name='historicalcarga',
            name='obs_comissao',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observação Comissão'),
        ),
        migrations.AlterField(
            model_name='cartaovp',
            name='cartao_base',
            field=models.CharField(choices=[('palmares', 'Palmares'), ('rio_grande', 'Granjas - RG'), ('jaguarao', 'Jaguarão')], default=corretora.models.get_last_cartao_base, max_length=17, verbose_name='Local Cartão'),
        ),
        migrations.AlterField(
            model_name='historicalcartaovp',
            name='cartao_base',
            field=models.CharField(choices=[('palmares', 'Palmares'), ('rio_grande', 'Granjas - RG'), ('jaguarao', 'Jaguarão')], default=corretora.models.get_last_cartao_base, max_length=17, verbose_name='Local Cartão'),
        ),
    ]
