# Generated by Django 2.2.8 on 2021-08-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0029_auto_20210725_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='comi_frete_ton',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor por tonelada', max_digits=5, null=True, verbose_name='Comissão Frete por Tonelada'),
        ),
        migrations.AddField(
            model_name='carga',
            name='gera_comi_frete',
            field=models.BooleanField(default=False, verbose_name='Gera comissão?'),
        ),
        migrations.AddField(
            model_name='historicalcarga',
            name='comi_frete_ton',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor por tonelada', max_digits=5, null=True, verbose_name='Comissão Frete por Tonelada'),
        ),
        migrations.AddField(
            model_name='historicalcarga',
            name='gera_comi_frete',
            field=models.BooleanField(default=False, verbose_name='Gera comissão?'),
        ),
    ]
