# Generated by Django 2.2.8 on 2021-08-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0031_auto_20210820_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='comi_frete_ton',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor por tonelada', max_digits=8, null=True, verbose_name='Comi Frete'),
        ),
        migrations.AlterField(
            model_name='carga',
            name='comi_frete_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor Total', max_digits=8, null=True, verbose_name='Comi F Total'),
        ),
        migrations.AlterField(
            model_name='historicalcarga',
            name='comi_frete_ton',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor por tonelada', max_digits=8, null=True, verbose_name='Comi Frete'),
        ),
        migrations.AlterField(
            model_name='historicalcarga',
            name='comi_frete_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor Total', max_digits=8, null=True, verbose_name='Comi F Total'),
        ),
    ]
