# Generated by Django 2.2.8 on 2021-08-21 20:28

import corretora.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0032_auto_20210820_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='comprovante_descarga',
            field=models.FileField(blank=True, null=True, upload_to=corretora.models.get_file_path_comprovantes, verbose_name='Comprovante Descarga'),
        ),
        migrations.AddField(
            model_name='carga',
            name='data_descarga',
            field=models.DateField(blank=True, default=None, help_text='dd/mm/aaaa', null=True, verbose_name='Data Descarga'),
        ),
        migrations.AddField(
            model_name='historicalcarga',
            name='comprovante_descarga',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Comprovante Descarga'),
        ),
        migrations.AddField(
            model_name='historicalcarga',
            name='data_descarga',
            field=models.DateField(blank=True, default=None, help_text='dd/mm/aaaa', null=True, verbose_name='Data Descarga'),
        ),
    ]
