# Generated by Django 2.2.8 on 2021-08-22 12:52

import corretora.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0033_auto_20210821_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpedido',
            name='pedido_arquivo',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Pedido '),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido_arquivo',
            field=models.FileField(blank=True, null=True, upload_to=corretora.models.get_file_path_pedidos, verbose_name='Pedido '),
        ),
    ]
