# Generated by Django 2.2.8 on 2021-08-24 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0036_transportadora_recebe_email_comprovante'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaCorretora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cnpj_cpf', models.CharField(help_text='digite apenas números', max_length=14, null=True, unique=True, verbose_name='CNPJ/CPF')),
                ('insc_estadual', models.CharField(help_text='digite apenas números', max_length=13, null=True, unique=True, verbose_name='Inscrição Estadual')),
                ('banco', models.CharField(blank=True, max_length=10, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, help_text='digite apenas números', max_length=5, verbose_name='Agencia')),
                ('conta', models.CharField(blank=True, help_text='digite apenas números', max_length=12, verbose_name='Conta')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('estado', models.TextField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernanbuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RS', 'Rio Grande do Sul'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=12, verbose_name='Estado')),
                ('obs', models.TextField(blank=True, max_length=500, verbose_name='Observação')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corretora.Cidade')),
            ],
            options={
                'verbose_name': 'Corretora',
                'verbose_name_plural': 'Corretoras',
            },
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='endereco',
        ),
        migrations.CreateModel(
            name='FaturaCargasComiFrete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número Fatura')),
                ('data_fatura', models.DateField(blank=True, default=None, help_text='dd/mm/aaaa', null=True, verbose_name='Data Fatura')),
                ('data_fatura_vencimento', models.DateField(blank=True, default=None, help_text='dd/mm/aaaa', null=True, verbose_name='Data Vencimento Fatura')),
                ('valor_total_fatura', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor Fatura')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='corretora.EmpresaCorretora')),
                ('transportadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='corretora.Transportadora')),
            ],
            options={
                'verbose_name': 'Fatura Terceiros',
                'verbose_name_plural': 'Faturas Terceiros',
            },
        ),
        migrations.AddField(
            model_name='carga',
            name='fatura_frete_terceiros',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corretora.FaturaCargasComiFrete'),
        ),
        migrations.AddField(
            model_name='historicalcarga',
            name='fatura_frete_terceiros',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corretora.FaturaCargasComiFrete'),
        ),
    ]
