# Generated by Django 2.2.8 on 2021-08-24 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corretora', '0037_auto_20210824_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFaturaCargasComiFrete',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criados', models.DateTimeField(blank=True, editable=False, verbose_name='Criação')),
                ('modificado', models.DateTimeField(blank=True, editable=False, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Número Fatura')),
                ('data_fatura', models.DateField(blank=True, default=None, help_text='dd/mm/aaaa', null=True, verbose_name='Data Fatura')),
                ('data_fatura_vencimento', models.DateField(blank=True, default=None, help_text='dd/mm/aaaa', null=True, verbose_name='Data Vencimento Fatura')),
                ('valor_total_fatura', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor Fatura')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corretora.EmpresaCorretora')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transportadora', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corretora.Transportadora')),
            ],
            options={
                'verbose_name': 'historical Fatura Terceiros',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
