# Generated by Django 2.2.8 on 2021-08-24 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0042_auto_20210824_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='fatura_frete_terceiros',
            field=models.ForeignKey(blank=True, limit_choices_to={'pagamento_fatura': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corretora.FaturaCargasComiFrete'),
        ),
        migrations.AlterField(
            model_name='historicalcarga',
            name='fatura_frete_terceiros',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'pagamento_fatura': False}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corretora.FaturaCargasComiFrete'),
        ),
    ]
