# Generated by Django 2.2.8 on 2021-08-29 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0043_auto_20210824_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='fatura_frete_terceiros',
            field=models.ForeignKey(blank=True, limit_choices_to={'pagamento_fatura': False}, null=True, on_delete=django.db.models.deletion.PROTECT, to='corretora.FaturaCargasComiFrete'),
        ),
    ]
