# Generated by Django 2.2.8 on 2021-08-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0044_auto_20210829_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpagamentofaturacargascomifrete',
            name='pagador',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Pagador'),
        ),
        migrations.AlterField(
            model_name='pagamentofaturacargascomifrete',
            name='pagador',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Pagador'),
        ),
    ]
