# Generated by Django 2.2.8 on 2021-09-03 16:55

import corretora.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0045_auto_20210831_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='nota_fiscal_arquivo',
            field=models.FileField(blank=True, null=True, upload_to=corretora.models.get_file_path_notafiscal, verbose_name='Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='historicalcarga',
            name='nota_fiscal_arquivo',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='email_notafiscal',
            field=models.EmailField(blank=True, max_length=30, verbose_name='E-mail Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='recebe_email_notafiscal',
            field=models.BooleanField(default=False, verbose_name='Recebe Nota Fiscal E-mail'),
        ),
    ]
