# Generated by Django 2.2.8 on 2021-09-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0047_auto_20210904_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='notafiscal',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='NF'),
        ),
        migrations.AlterField(
            model_name='historicalcarga',
            name='notafiscal',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='NF'),
        ),
    ]
