# Generated by Django 2.2.8 on 2021-09-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0048_auto_20210907_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email_notafiscal_1',
            field=models.EmailField(blank=True, max_length=50, verbose_name='E-mail Nota Fiscal 1'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_notafiscal_2',
            field=models.EmailField(blank=True, max_length=50, verbose_name='E-mail Nota Fiscal 2'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_notafiscal_3',
            field=models.EmailField(blank=True, max_length=50, verbose_name='E-mail Nota Fiscal 3'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_notafiscal_4',
            field=models.EmailField(blank=True, max_length=50, verbose_name='E-mail Nota Fiscal 4'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_notafiscal_5',
            field=models.EmailField(blank=True, max_length=50, verbose_name='E-mail Nota Fiscal 5'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='recebe_email_notafiscal',
            field=models.BooleanField(default=False, verbose_name='Recebe Nota Fiscal E-mail'),
        ),
    ]
