# Generated by Django 2.2.8 on 2021-09-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0050_auto_20210913_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpagamentofaturacargascomifrete',
            name='conta_pagadora',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Conta Pagador'),
        ),
        migrations.AlterField(
            model_name='pagamentofaturacargascomifrete',
            name='conta_pagadora',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Conta Pagador'),
        ),
    ]
