# Generated by Django 2.2.8 on 2021-09-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0053_auto_20210917_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='obs_email_nf',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observação Descarga'),
        ),
        migrations.AddField(
            model_name='historicalcarga',
            name='obs_email_nf',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observação Descarga'),
        ),
    ]
