# Generated by Django 2.2.8 on 2021-09-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0055_auto_20210925_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='motorista',
            field=models.CharField(max_length=40, verbose_name='Motorista'),
        ),
        migrations.AlterField(
            model_name='historicalcarga',
            name='motorista',
            field=models.CharField(max_length=40, verbose_name='Motorista'),
        ),
    ]
