# Generated by Django 2.2.8 on 2021-10-19 02:51

import corretora.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0056_auto_20210928_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaovp',
            name='cartao_base',
            field=models.CharField(choices=[('palmares', 'Palmares'), ('rio_grande', 'Granjas - RG'), ('jaguarao', 'Jaguarão'), ('cerati_uruguaiana', 'Ceratti')], default=corretora.models.get_last_cartao_base, max_length=17, verbose_name='Local Cartão'),
        ),
        migrations.AlterField(
            model_name='historicalcartaovp',
            name='cartao_base',
            field=models.CharField(choices=[('palmares', 'Palmares'), ('rio_grande', 'Granjas - RG'), ('jaguarao', 'Jaguarão'), ('cerati_uruguaiana', 'Ceratti')], default=corretora.models.get_last_cartao_base, max_length=17, verbose_name='Local Cartão'),
        ),
    ]
