# Generated by Django 4.0.1 on 2022-06-26 17:02

import corretora.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0057_auto_20211018_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcarga',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Carga', 'verbose_name_plural': 'historical Cargas'},
        ),
        migrations.AlterModelOptions(
            name='historicalcartaovp',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Cartão VP', 'verbose_name_plural': 'historical Cartoēs VP'},
        ),
        migrations.AlterModelOptions(
            name='historicaldatasemcarga',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Data Sem Descarga', 'verbose_name_plural': 'historical Datas Sem Descarga'},
        ),
        migrations.AlterModelOptions(
            name='historicalemailstransportadora',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Email Transportadora', 'verbose_name_plural': 'historical Emails Transportadora'},
        ),
        migrations.AlterModelOptions(
            name='historicalfaturacargascomifrete',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Fatura Terceiros', 'verbose_name_plural': 'historical Faturas Terceiros'},
        ),
        migrations.AlterModelOptions(
            name='historicalpagamentofaturacargascomifrete',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Pagamento Fatura Terceiros', 'verbose_name_plural': 'historical Pagamentos Faturas Terceiros'},
        ),
        migrations.AlterModelOptions(
            name='historicalpedido',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Pedido', 'verbose_name_plural': 'historical Pedidos'},
        ),
        migrations.AlterField(
            model_name='cartaovp',
            name='cartao_base',
            field=models.CharField(choices=[('palmares', 'Palmares'), ('rio_grande', 'Granjas - RG'), ('jaguarao', 'Jaguarão'), ('cerati_uruguaiana', 'Ceratti'), ('antonio_uruguaiana', 'Antonio B.')], default=corretora.models.get_last_cartao_base, max_length=20, verbose_name='Local Cartão'),
        ),
        migrations.AlterField(
            model_name='historicalcarga',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcartaovp',
            name='cartao_base',
            field=models.CharField(choices=[('palmares', 'Palmares'), ('rio_grande', 'Granjas - RG'), ('jaguarao', 'Jaguarão'), ('cerati_uruguaiana', 'Ceratti'), ('antonio_uruguaiana', 'Antonio B.')], default=corretora.models.get_last_cartao_base, max_length=20, verbose_name='Local Cartão'),
        ),
        migrations.AlterField(
            model_name='historicalcartaovp',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaldatasemcarga',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalemailstransportadora',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfaturacargascomifrete',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpagamentofaturacargascomifrete',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
